CREATE ROLE finance_app_user WITH LOGIN PASSWORD 'finance_pass' NOSUPERUSER;

GRANT USAGE ON SCHEMA public TO finance_app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO finance_app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO finance_app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO finance_app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT USAGE, SELECT ON SEQUENCES TO finance_app_user;